create table public.users (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_name character varying null,
  user_id uuid null default gen_random_uuid (),
  role boolean null default false,
  constraint users_pkey primary key (id),
  constraint users_user_id_fkey foreign KEY (user_id) references auth.users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create materialized view public.user_data_view as
select
  p.id,
  p.user_id,
  p.user_name,
  a.email,
  p.role
from
  users p
  join auth.users a on p.user_id = a.id;

  create table public.adventures (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id bigint null,
  intro text null,
  constraint adventures_pkey primary key (id),
  constraint adventures_user_id_fkey foreign KEY (user_id) references users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

  create view public.user_adventures as
select
  u.id,
  u.user_name,
  a.id as adventure_id,
  a.intro
from
  users u
  join adventures a on u.id = a.user_id;


  create table public.cards (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  power bigint null,
  mana_cost bigint null,
  type text null default 'attack'::text,
  name text null,
  description text null,
  is_poison bigint null,
  is_burn bigint null,
  is_def_amp bigint null,
  is_crit_amp bigint null,
  is_agil_amp bigint null,
  is_def_debuff bigint null,
  is_agil_debuff bigint null,
  turn_count bigint null,
  is_stunned boolean null default false,
  img text null,
  modal_bg text null,
  draw_chance numeric null,
  is_mana bigint null default '0'::bigint,
  video_src text null,
  rarity text null default 'commun'::text,
  video_modal text null,
  constraint cards_pkey primary key (id)
) TABLESPACE pg_default;

create index IF not exists idx_card_name on public.cards using btree (name) TABLESPACE pg_default;

create view public.total_card_count as
select
  count(*) as total_count
from
  cards;

  create table public.characters (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name character varying null default 'Kidlat'::character varying,
  health bigint null default '0'::bigint,
  mana bigint null default '0'::bigint,
  agility numeric null default '0'::numeric,
  defense numeric null default '0'::numeric,
  critical_rate numeric null default '0'::numeric,
  tagline text null default ''::text,
  lore text null,
  user_id bigint null,
  adventure_id bigint null,
  wisdom bigint null default '0'::bigint,
  gold bigint null default '0'::bigint,
  constraint characters_pkey primary key (id),
  constraint characters_adventure_id_fkey foreign KEY (adventure_id) references adventures (id) on update CASCADE on delete CASCADE,
  constraint characters_user_id_fkey foreign KEY (user_id) references users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

  create table public.structure_decks (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  title text null,
  description character varying null,
  character_id bigint null,
  img text null,
  constraint structure_decks_pkey primary key (id),
  constraint structure_decks_character_id_fkey foreign KEY (character_id) references characters (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;


create table public.scenarios (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  scene text null,
  user_id bigint null,
  choice character varying null,
  adventure_id bigint null,
  constraint scenarios_pkey primary key (id),
  constraint scenarios_adventure_id_fkey foreign KEY (adventure_id) references adventures (id) on update CASCADE on delete CASCADE,
  constraint scenarios_user_id_fkey foreign KEY (user_id) references users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.rooms (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  character_id bigint null,
  room_name text null,
  player_1 bigint null,
  player_2 bigint null,
  constraint sessions_pkey primary key (id),
  constraint rooms_player_1_fkey foreign KEY (player_1) references users (id),
  constraint rooms_player_2_fkey foreign KEY (player_2) references users (id),
  constraint sessions_character_id_fkey foreign KEY (character_id) references characters (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.quests (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  done boolean null,
  description text null,
  user_id bigint null,
  gold bigint null,
  card_id bigint null,
  title character varying null,
  constraint quests_pkey primary key (id),
  constraint quests_card_id_fkey foreign KEY (card_id) references cards (id),
  constraint quests_user_id_fkey foreign KEY (user_id) references users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.enemies (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  health bigint null,
  mana bigint null,
  agility bigint null,
  defense bigint null,
  critical_rate bigint null,
  wisdom bigint null,
  name character varying null,
  constraint enemies_pkey primary key (id)
) TABLESPACE pg_default;


create table public.decks (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  card_id bigint null,
  structure_deck_id bigint null,
  constraint decks_pkey primary key (id),
  constraint decks_card_id_fkey foreign KEY (card_id) references cards (id) on update CASCADE on delete CASCADE,
  constraint decks_structure_deck_id_fkey foreign KEY (structure_deck_id) references structure_decks (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.deck_builds (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id bigint null,
  card_id bigint null,
  adventure_id bigint null,
  character_id bigint null,
  temp bigint null,
  constraint deck_builds_pkey primary key (id),
  constraint deck_builds_adventure_id_fkey foreign KEY (adventure_id) references adventures (id) on update CASCADE on delete CASCADE,
  constraint deck_builds_card_id_fkey foreign KEY (card_id) references cards (id) on update CASCADE on delete CASCADE,
  constraint deck_builds_character_id_fkey foreign KEY (character_id) references characters (id) on update CASCADE on delete CASCADE,
  constraint deck_builds_user_id_fkey foreign KEY (user_id) references users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.cards_owned (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id bigint null,
  character_id bigint null,
  card_id bigint null,
  constraint cards_owned_pkey primary key (id),
  constraint cards_owned_card_id_fkey foreign KEY (card_id) references cards (id) on update CASCADE on delete CASCADE,
  constraint cards_owned_character_id_fkey foreign KEY (character_id) references characters (id) on update CASCADE on delete CASCADE,
  constraint cards_owned_user_id_fkey foreign KEY (user_id) references users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create materialized view public.card_rarity_counts as
select
  cards.rarity,
  count(*) as count
from
  cards
group by
  cards.rarity;